version: "2"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cm3
      - MYSQL_DATABASE=cm3db
      - MYSQL_USER=as
      - MYSQL_PASSWORD=as4as
    ports:
      - "4202:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  app:
    build:
      context: ./web-app
    ports:
      - "4200:8080"
      - "4201:9990"
    depends_on:
      - db
    links:
      - db
    dns: 8.8.8.8
  wildfly:
    image: jboss/wildfly
