<!DOCTYPE html>
<html lang="pl-PL">

<head>

    <title>Delegacje</title>

    <meta http-equiv="refresh" content="2;url=http://localhost:8080/delegations-web/mainMenu"/>

<#include "../include/headAndMeta.ftlh">

</head>

<body style="font-family: 'Open Sans', sans-serif">

<#--<#include "../include/settingNavBarRole.ftlh">-->

<div class="container" style="margin-top: 115px">
    <div class="row">
        <div class="col">
            <div class="alert alert-secondary" role="alert" style="width:60%;margin: auto; text-align: center">
                <h4 class="alert-heading"><b>DELEGACJA WYSŁANA</b><br/>Nastąpi przekierowanie na stronę główną.</h4>
            </div>
        </div>
    </div>
</div>

<#include "../include/scripts.ftlh">
<#include "../include/footer.ftlh">

</body>
</html>