<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <title>Main menu</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<#--bootstrap
    -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
        .footer {
            position: absolute;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 2px;
            background-color: #efefef;
            text-align: center;
            height: 25px;
        }
    </style>
</head>
<body style="font-family: 'Open Sans', sans-serif; text-align: center">
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/delegations-web/mainMenu"> &#9992 delegations-web.com</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/delegations-web/myDelegations">Moje delegacje</a></li>
                <li><a href="/delegations-web/addForm">Dodaj delegację</a></li>
                <li><a href="/delegations-web/searchDelegations">Szukaj delegacji</a></li>
                <li><a href="/delegations-web/manageDelegations">Zarządzaj delegacjami</a></li>
                <li><a href="/delegations-web/contact">Kontakt</a></li>
                <li><a href="/delegations-web/about">O nas</a></li>
                <li>
                    <a href="/delegations-web/sign-in" class="btn btn-default btn-outline btn-circle">Wyloguj się</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container" style="width: 50%; text-align: center; margin-top: 100px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Witaj użytkowniku!</div>
                <div class="panel-body">
                    <table class="table table-borderless">
                        <thead>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">Imię i nazwisko</th>
                            <td>Jan Kowalski</td>
                        </tr>
                        <tr>
                            <th scope="row">Stanowisko</th>
                            <td>Kierownik działu HR</td>
                        </tr>
                        <tr>
                            <th scope="row">Nazwa firmy</th>
                            <td>Firma A</td>
                        </tr>
                        <tr>
                            <th scope="row">Adres firmy</th>
                            <td>adres firmy A</td>
                        </tr>
                        <tr>
                            <th scope="row">Ilość wniosków:</th>
                            <td>0</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer">
    <p class="float">&copy; 2018 Kurs InfoShare Academy &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

