<!DOCTYPE html>
<html lang="pl-PL">
<head>

    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Welcome</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>

        html{
            display: flex;
            flex-flow: row nowrap;
            justify-content: center;
            align-content: center;
            align-items: center;
            height:100%;
            margin: 0;
            padding: 0;
            background:#eeeeee;
        }
        body {
            margin: 0;
            flex: 0 1 auto;
            align-self: auto;
            width: 100%
            max-width: 900px;
            max-height: 600px;
            background:#fafafa;
            -webkit-box-shadow: 0px 0px 96px 0px rgba(0,0,0,0.75);
            -moz-box-shadow: 0px 0px 96px 0px rgba(0,0,0,0.75);
            box-shadow: 0px 0px 96px 0px rgba(0,0,0,0.75);
        }
        .container-fluid {
            height: 35vh;
            overflow: auto;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .container-fluid2 {
            height: 15vh;
            overflow: auto;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .row {
            width: 750px;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        p {
            color:gray;
            font-style: italic;
        }

        a {
            text-decoration: none;
            color: #ffffff;
        }

        a:hover {
            text-decoration: none;
            color: #ffffff;
        }

    </style>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/comfortable.png" alt="comfortable" style="width:100%">
                    <div class="caption">
                        <p class="text-center">If you want to travel comfortably</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/ontime.png" alt="ontime" style="width:100%">
                    <div class="caption">
                        <p class="text-center">If you do not want to represent your team well</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/fast.png" alt="fast" style="width:100%">
                    <div class="caption">
                        <p class="text-center">If you never want to wait for important meetings</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid2">
    <div class="row">
        <div class="col-md-2">
            <div class="thumbnail">
                <button type="button" class="btn btn-secondary">
                <a href="/delegations-web/sign-up">Sign up</a>
                </button>
            </div>
        </div>
        <div class="col-md-2">
            <div class="thumbnail">
                <button type="button" class="btn btn-secondary">
                    <a href="/delegations-web/sign-in">Sign in</a>
                </button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

