<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <title>Witaj!</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<#--bootstrap
    -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<style>
    p.text-center {
        font-style: italic;
        font-family: 'Open Sans', sans-serif;
    }
     .footer {
         position: absolute;
         right: 0;
         bottom: 0;
         left: 0;
         padding: 2px;
         background-color: #efefef;
         text-align: center;
         height: 25px;
     }
</style>
</head>
<body style="font-family: 'Open Sans', sans-serif">
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/delegations-web/"> &#9992 delegations-web.com</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/delegations-web/sign-in" class="btn btn-default btn-outline btn-circle">Zaloguj się</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container" style="margin-top: 50px; width: 60%">
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/comfortable.png" alt="comfortable" style="width:100%">
                    <div class="caption">
                        <p class="text-center">Wygoda</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/ontime.png" alt="ontime" style="width:100%">
                    <div class="caption">
                        <p class="text-center">Punktualność</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                    <img src="images/fast.png" alt="fast" style="width:100%">
                    <div class="caption">
                        <p class="text-center">Szybkość</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<footer class="footer">
    <p class="float">&copy; 2018 Kurs InfoShare Academy &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

